### ISSUE TITLE
Clear limit between instructor and student

### ISSUE THREAD

**Issue by Alinlish** [websquared/learnformula-cloud-issues#30]
I propose to make a clear limit beween instructor and student. For example, after one account can be set only as instructor or only as student. This can be changed on profile page. For one of my accounts, I selected that I want to learn, but I am also able to add an instructor account. The limit should be clear, and I should only learn or only train/add courses [Link](https://www.screencast.com/t/BsfIM3GUmT)

**Comment by websquared** [comment]
This was made intentional - because even instructors might take other courses. In future we will add default courses for instructors to take, like "How to create a course"
