### ISSUE TITLE
SUGGESTION - next button

### ISSUE THREAD

**Issue by MarionneLourdes** [websquared/learnformula-cloud-issues#4]
When creating a course,

![image](https://user-images.githubusercontent.com/40473732/41986457-c4ef0218-7a68-11e8-99d7-b953dda86e37.png)

And you are done with a tab, let's say "landing page", it would be better if there is a next button or it will proceed to the next tab right away, which is "content". Because what happens is that after saving it will remain on the page and you have to manually click on the next one to proceed.

**Comment by websquared** [comment]
done
