### ISSUE TITLE
CREDIT CARD PAYMENT - DECLINED

### ISSUE THREAD

**Issue by MarionneLourdes** [websquared/learnformula-cloud-issues#40]
![image](https://user-images.githubusercontent.com/40473732/42164007-33da7f14-7e37-11e8-821b-292c2e1e9773.png)

When test card was used, payment will not push through.

**Comment by websquared** [comment]
This test card can be used only on dev site learnformula.space, it won't work on learnformula.com - only actual valid CC will work there
